name: results
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  #  di
  get_it: ^4.0.1
  injectable: ^0.3.0
  # network
  retrofit: ^1.3.4
  json_serializable: ^3.3.0
  connectivity: ^0.4.8+2
  data_connection_checker: ^0.3.4
  logger: ^0.9.1
  # state management
  provider: ^4.0.5
  # navigation
  auto_route: ^0.4.4
  # util
  freezed_annotation: ^0.7.1
  shared_preferences: ^0.5.7
  flushbar: ^1.10.0
  flutter_svg: ^0.17.4
  date_format: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  # di
  injectable_generator: ^0.3.4
  # network
  retrofit_generator: ^1.3.4+1
  # navigation
  auto_route_generator: ^0.4.5
  # util
  freezed: ^0.10.7


flutter:

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
