name: results
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3
  #  di
  get_it: ^4.0.2
  injectable: ^0.3.0
  # network
  retrofit: ^1.3.4
  json_serializable: ^3.3.0
  connectivity: ^0.4.8+2
  data_connection_checker: ^0.3.4
  logger: ^0.9.1
  # state management
  provider: ^4.0.5+1
  # navigation
  auto_route: ^0.4.5
  # util
  freezed_annotation: ^0.7.1
  flushbar: ^1.10.0
  flutter_svg: ^0.17.4
  implicitly_animated_reorderable_list: ^0.1.10
  carousel_slider: ^2.0.0
  kt_dart: ^0.7.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.9.0
  # di
  injectable_generator: ^0.3.5
  # network
  retrofit_generator: ^1.3.4+1
  # navigation
  auto_route_generator: ^0.4.8
  # util
  freezed: ^0.10.7


flutter:

  uses-material-design: true

  assets:
    - lang/
    - fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Barlow
      fonts:
        - asset: fonts/Barlow/Barlow-Thin.ttf
          style: normal
          weight: 100
        - asset: fonts/Barlow/Barlow-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: fonts/Barlow/Barlow-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: fonts/Barlow/Barlow-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: fonts/Barlow/Barlow-Light.ttf
          style: normal
          weight: 300
        - asset: fonts/Barlow/Barlow-LightItalic.ttf
          style: italic
          weight: 300
        - asset: fonts/Barlow/Barlow-Regular.ttf
          style: normal
          weight: 400
        - asset: fonts/Barlow/Barlow-Italic.ttf
          style: italic
          weight: 400
        - asset: fonts/Barlow/Barlow-Medium.ttf
          style: normal
          weight: 500
        - asset: fonts/Barlow/Barlow-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: fonts/Barlow/Barlow-SemiBold.ttf
          style: normal
          weight: 600
        - asset: fonts/Barlow/Barlow-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: fonts/Barlow/Barlow-Bold.ttf
          style: normal
          weight: 700
        - asset: fonts/Barlow/Barlow-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: fonts/Barlow/Barlow-ExtraBold.ttf
          style: normal
          weight: 800
        - asset: fonts/Barlow/Barlow-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: fonts/Barlow/Barlow-Black.ttf
          style: normal
          weight: 900
        - asset: fonts/Barlow/Barlow-BlackItalic.ttf
          style: italic
          weight: 900
